# Top level makefile for running simulation

# Boilerplate top level call.  Must include the top level CONFIG
# Once the build directory has been created this Makefile will be invoked again
# with PROJECT_TOP set to this directory.
ifndef PROJECT_TOP
include ../../CONFIG
$(info FPGA_COMMON = $(FPGA_COMMON))
include $(FPGA_COMMON)/makefiles/Makefile.sim
else

endif
