# Special functions for working with generated paths

# This has to be included as a .tcl script instead of a .xdc because of the use
# of foreach.

# Set false path to all registers marked with this custom attribute.  This is
# generally only used with util/sync_bit.vhd
set cells [get_cells -hierarchical -filter { false_path_to == "TRUE" }]
if [llength $cells] { set_false_path -to $cells }

# Similarly for from attributes, needed for some reset registers.
set cells [get_cells -hierarchical -filter { false_path_from == "TRUE" }]
if [llength $cells] { set_false_path -from $cells }

# Special match against distributed memory generated by memory_array_dual: in
# the particular case of inferring distributed memory we need to set a false
# path from all of the inferred cells.
set cells [get_cells -hier -filter {
    NAME =~ */memory_array_dual_memory*  &&  REF_NAME =~ RAMD*}]
if [llength $cells] { set_false_path -from $cells }

# Max delay constraint.  Each cell with max_delay_from must specify the maximum
# allowed delay in ns, this needs to be applied individually to each cell
foreach cell [get_cells -hierarchical -filter { max_delay_from != "" }] {
    set_max_delay [get_property max_delay_from $cell] \
        -datapath_only -from $cell
}

unset cells

# vim: set filetype=tcl:
