from __future__ import print_function

import sys
import numpy


# The target block ram is 2048*18
LOOKUP_BITS = 11
STORED_BITS = 17

SAMPLES = 1 << LOOKUP_BITS


def generate_result():
    A = numpy.arange(SAMPLES) + SAMPLES
    B = numpy.int32(numpy.round(2**(LOOKUP_BITS + STORED_BITS) / A))
    # We hack the first result to fit into 17 bits
    B[0] = 0x1FFFF
    return B


def print_result(result):
    for r in result[:-1]:
        print('        17X"%05x",' % r)
    print('        17X"%05x"' % result[-1])

def generate_body():
    print_result(generate_result())


print('''\
--
-- DO NOT EDIT THIS FILE !!!
--
-- This file has been automatically generated.
-- To change this file edit the source file and rebuild.
''')
for line in open(sys.argv[1]):
    if '@TABLE_BODY@' in line:
        generate_body()
    else:
        print(line, end = '')
