# Makefile for launching simulation

CLASS = sim
BUILD_PATTERN = /$(COMPONENT_NAME)
FPGA_TOP := $(realpath $(CURDIR)/../..)
include $(FPGA_COMMON)/makefiles/Makefile.delegate

# vim: set filetype=make:
